#!/usr/bin/env python
# Copyright 2014 David Irvine
#
# This file is part of Loguino
#
# Loguino is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Loguino is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Loguino.  If not, see "http://www.gnu.org/licenses/".
#
#


init = ""
for pin in range(54):
    init += """
        #ifdef DP_SAMPLE_PIN_%d
            #ifdef DEBUG_DIGITAL_POLLER
                DEBUG_5("Setting pin %d to input");
            #endif
            pinMode(%d, INPUT);
            #ifdef DEBUG_DIGITAL_POLLER
                DEBUG_3("Successfully set pin %f to input");
            #endif
            #ifdef DP_HOLD_PIN_%d_HIGH
                #ifdef DEBUG_DIGITAL_POLLER
                    DEBUG_5("Setting pin %d pullup HIGH");
                #endif
                digitalWrite(%d,HIGH);
                #ifdef DEBUG_DIGITAL_POLLER
                    DEBUG_3("Successfully set pin %d pullup HIGH");
                #endif
            #elif
                #ifdef DEBUG_DIGITAL_POLLER
                    DEBUG_5("Setting pin %d pullup LOW");
                #endif
                digitalWrite(%d,LOW);
                #ifdef DEBUG_DIGITAL_POLLER
                    DEBUG_3("Successfully set pin %d pullup LOW");
                #endif
            #endif
        #endif""" % (pin, pin, pin, pin, pin, pin, pin, pin, pin, pin, pin)

sample = ""
for pin in range(54):
    sample += """
        #ifdef DP_SAMPLE_PIN_%d
            #ifdef DEBUG_DIGITAL_POLLER
                DEBUG_5("Reading value for pin %d");
            #endif
            dstate = digitalRead(%d);
            #ifdef DEBUG_DIGITAL_POLLER
                DEBUG_3("Sucessfully read value for pin %d");
            #endif
            #ifdef DP_INVERT_PIN_%d
                #ifdef DEBUG_DIGITAL_POLLER
                    DEBUG_5("Inverting value for pin %d");
                #endif
                dstate = !dstate;
                #ifdef DEBUG_DIGITAL_POLLER
                    DEBUG_3("Successfully inverted value for pin %d");
                #endif
            #endif
            #ifdef DEBUG_DIGITAL_POLLER
                DEBUG_5("Logging value for pin %d");
            #endif
            logMessage(DP_PIN_%d_NAME, dstate ? "On" : "Off", "N/A");
            #ifdef DEBUG_DIGITAL_POLLER
                DEBUG_2("Successfully logged value for pin %d");
            #endif
        #endif
        """ % (pin, pin, pin, pin, pin, pin, pin, pin, pin, pin)


code = """
/* Copyright 2014 David Irvine
 *
 * This file is part of Loguino
 *
 * Loguino is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Loguino is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with Loguino.  If not, see "http://www.gnu.org/licenses/".
 *
*/




#ifdef ENABLE_DIGITAL_POLLER
    void digital_pin_init(){
        DEBUG_1("Starting");
%s
        DEBUG_1("Finished");
    }

    void digital_pin_sample(){
        DEBUG_1("Starting");
        int dstate;
%s
        DEBUG_1("Finished");
    }
#endif
""" % (init, sample)

f = open("code.c", "w")
f.write(code)
f.close()

config="""
/* Copyright 2014 David Irvine
 *
 * This file is part of Loguino
 *
 * Loguino is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Loguino is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with Loguino.  If not, see "http://www.gnu.org/licenses/".
 *
*/




#define ENABLE_DIGITAL_POLLER
#define DEBUG_DIGITAL_POLLER
"""
for pin in range(54):
    config += """
#define DP_SAMPLE_PIN_%d
#define DP_HOLD_PIN_%d_HIGH
#define DP_INVERT_PIN_%d
#define DP_PIN_%d_NAME "dp.pin%d"
""" % (pin, pin, pin, pin, pin)

f=open("config.c","w")
f.write(config)
f.close()
