#!/usr/bin/env python
# Copyright 2014 David Irvine
#
# This file is part of Loguino
#
# Loguino is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Loguino is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Loguino.  If not, see "http://www.gnu.org/licenses/".
#
#


init = ""
for pin in range(16):
    if pin >= 6 and pin < 12 :
        init += """#if defined(__AVR_ATmega32U4__) || defined(__AVR_ATmega2560__)\n"""
    elif pin >= 12:
        init += """#if defined(__AVR_ATmega2560__)\n"""
    init += """
        #ifdef AP_SAMPLE_PIN_%d
            #ifdef DEBUG_ANALOG_POLLER
                DEBUG_5("Setting pin %d to input");
            #endif
            pinMode(%d, INPUT);
            #ifdef DEBUG_ANALOG_POLLER
                DEBUG_3("Successfully set pin A%d to input");
            #endif
            #ifdef AP_HOLD_PIN_%d_HIGH
                #ifdef DEBUG_ANALOG_POLLER
                    DEBUG_5("Setting pin %d pullup HIGH");
                #endif
                digitalWrite(A%d,HIGH);
                #ifdef DEBUG_ANALOG_POLLER
                    DEBUG_3("Successfully set pin A%d pullup HIGH");
                #endif
            #elif
                #ifdef DEBUG_ANALOG_POLLER
                    DEBUG_5("Setting pin A%d pullup LOW");
                #endif
                digitalWrite(A%d,LOW);
                #ifdef DEBUG_ANALOG_POLLER
                    DEBUG_3("Successfully set pin A%d pullup LOW");
                #endif
            #endif
        #endif
        """ % (pin, pin, pin, pin, pin, pin, pin, pin, pin, pin, pin)
    if pin >= 6:
        init += """#endif\n"""

sample = ""
for pin in range(16):
    if pin >= 6 and pin < 12 :
        sample += """#if defined(__AVR_ATmega32U4__) || defined(__AVR_ATmega2560__)\n"""
    elif pin >= 12:
        sample += """#if defined(__AVR_ATmega2560__)\n"""
    sample += """
            #ifdef AP_SAMPLE_PIN_%d
                #ifdef DEBUG_ANALOG_POLLER
                    DEBUG_5("Reading value for pin %d");
                #endif
                logMessage(AP_PIN_%d_NAME, analogRead(%d), "(volts * 5)/1024");
                #ifdef DEBUG_DIGITAL_POLLER
                    DEBUG_2("Sucessfully read and logged value for pin %d");
                #endif
            #endif
        """ % (pin, pin, pin, pin, pin)
    if pin >= 6:
        sample += """#endif\n"""

code = """
/* Copyright 2014 David Irvine
 *
 * This file is part of Loguino
 *
 * Loguino is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Loguino is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with Loguino.  If not, see "http://www.gnu.org/licenses/".
 *
*/




#ifdef ENABLE_ANALOG_POLLER
    void analog_pin_init(){
        DEBUG_1("Starting");
        #ifdef ANALOG_USE_EXTERN_REF
            analogReference(EXTERNAL);
        #endif
%s
        DEBUG_1("Finished");
    }

    void analog_pin_sample(){
        DEBUG_1("Starting");
%s
        DEBUG_1("Finished");
    }
#endif
""" % (init, sample)

f = open("code.c", "w")
f.write(code)
f.close()

config="""
/* Copyright 2014 David Irvine
 *
 * This file is part of Loguino
 *
 * Loguino is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Loguino is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with Loguino.  If not, see "http://www.gnu.org/licenses/".
 *
*/


// If enabled, Loguino will poll analog pins for their value each iteration.
//#define ENABLE_ANALOG_POLLER

// If defined, debug messages shall be enabled for this poller
//#define DEBUG_ANALOG_POLLER

// If enabled, will use the external reference voltage.
// See: http://arduino.cc/en/Reference/AnalogReference
// #define ANALOG_USE_EXTERN_REF
"""
for pin in range(16):
    config += """
// ----- PIN: %d -----

// If enabled, Analog Pin %d will be polled.
//#define AP_SAMPLE_PIN_%d

// If enabled, this pullup resistor will be enabled on this pin.
#define AP_HOLD_PIN_%d_HIGH

// The name to use when logging this pin
#define AP_PIN_%d_NAME "ap.pin%d"

""" % (pin, pin, pin, pin, pin, pin)

f=open("config.c","w")
f.write(config)
f.close()
